In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
flat = arr.flatten()
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
flat[0]

np.int64(1)

In [12]:
flat[3: 10]

array([ 4,  5,  6,  7,  8,  9, 10])

In [13]:
b = flat[3:7]  #does not create a new array or a copy but slicing return only a view

In [14]:
b

array([4, 5, 6, 7])

In [15]:
b[0] = 69 #making changes in slicing view will affect the original array

In [16]:
b

array([69,  5,  6,  7])

In [17]:
flat

array([ 1,  2,  3, 69,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
b = flat[3:7].copy()

In [19]:
b

array([69,  5,  6,  7])

In [20]:
b[0] = 4

In [21]:
b

array([4, 5, 6, 7])

In [22]:
flat

array([ 1,  2,  3, 69,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
#Exercise
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)

(3, 3)


In [27]:
arr1 = np.array([1.1,2.2,3.3])
arr1
arr1 = arr1.astype(int)
print(arr1)
print(arr1.dtype)

[1 2 3]
int64


In [30]:
arr2 = np.array([1,2,3,4,5,6])
print(arr2[[1,3,5]])

[2 4 6]


In [34]:
arr2 = np.array( [1,2,3,4,5,6,7,8,9] )
arr2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])